### ISSUE TITLE
可否支持多个请求头字段

### ISSUE THREAD

**Issue by zyf8827** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#12]
我的使用场景下需要赋值多个header，可否考虑支持。

**Comment by shouldnotappearcalm** [comment]
是否升级到了最新的 `1.2.2`，以前版本可能有点 `bug`

**Comment by shouldnotappearcalm** [comment]
@zyf8827

**Comment by zyf8827** [comment]
我这里已经是1.2.2版本，我的需求是请求头字段可以加多个，现在界面上固定只能设置一个字段，比如需要在header里面加token和user_id两个字段

![image](https://user-images.githubusercontent.com/5118661/76275412-3292a100-62be-11ea-8c33-4031bdd7b96c.png)

**Comment by shouldnotappearcalm** [comment]
@zyf8827 这应该还是一个没有完全修复的 `bug`，您现在新建一个环境配置中的环境，再来接口自动鉴权这设置新环境的鉴权，你在 `header` 输入第一行的时候会自动添加第二行

**Comment by zyf8827** [comment]
@shouldnotappearcalm 已升级1.2.3版本，按您写的操作，还是无法添加第二行
![image](https://user-images.githubusercontent.com/5118661/76276808-d6318080-62c1-11ea-993b-0bc93ff016d8.png)

**Comment by shouldnotappearcalm** [comment]
您加下我 `vx` 吧， `Z3pyMTE5MTQ2NTA5Nw==`，base64

**Comment by shouldnotappearcalm** [comment]
之前理解错了，您的需求是想把结果设置到多个 `Header` 里，等待下个版本实现此功能
