### ISSUE TITLE
配置一直显示地址错误

### ISSUE THREAD

**Issue by blackkeai** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#14]
获取token地址不正确

![image](https://user-images.githubusercontent.com/7159046/78226498-5f715700-74fe-11ea-9aba-085fe96a5b7e.png)

**Comment by akhuang** [comment]
改下源码，把具体的错误打出来看下

controller.js 第157行，可以看到具体的错误

**Comment by empl123** [comment]
你好，我也遇到了这个问题，你的这个问题解决了吗？若果解决了，帮忙给我说一下解决方案，我搞了好长时间了。谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！谢谢！

**Comment by shouldnotappearcalm** [comment]
@empl123 截图看看你的配置

**Comment by empl123** [comment]
![image](https://user-images.githubusercontent.com/23521894/80168518-a5a96a00-8615-11ea-9664-03fe42289253.png)
谢谢了！谢谢了！谢谢了！谢谢了！谢谢了！谢谢了！

**Comment by empl123** [comment]
我吧地址填写完后一直转圈圈如下图：
![image](https://user-images.githubusercontent.com/23521894/80169045-fa011980-8616-11ea-8099-6d75938e2189.png)
然后就出现获取token地址不正确等问题了，如下图：
![image](https://user-images.githubusercontent.com/23521894/80169122-359be380-8617-11ea-8690-15513116792d.png)
帮忙看看，谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！谢谢谢谢！

**Comment by empl123** [comment]
@shouldnotappearcalm 我把截图提出来了，你帮忙看一下！！

**Comment by shouldnotappearcalm** [comment]
这个地址用 postman 能正常请求么

**Comment by blackkeai** [comment]
我当时是用 chrome 隐身模式就好了，我的是缓存问题，你可以尝试一下。

**Comment by empl123** [comment]
@shouldnotappearcalm 正常的，如下图：
![image](https://user-images.githubusercontent.com/23521894/80170774-59612880-861b-11ea-8d06-1b2c86a8cbbc.png)

**Comment by empl123** [comment]
@blackkeai 谢谢了，搞了好长时间了，不知道是哪里的问题，不知道是接口自动鉴权的插件没安装成功还是配置的有问题，我试试你或的办法。还有yapi高版本的google浏览器好像使用不了，运行测试的时候？是吗？

**Comment by empl123** [comment]
@shouldnotappearcalm postman 请求试正常的。如下图：
![image](https://user-images.githubusercontent.com/23521894/80171059-0340b500-861c-11ea-9f88-715dbc334fd3.png)

**Comment by shouldnotappearcalm** [comment]
看下你 postman 的请求体呢

**Comment by blackkeai** [comment]
我就用的最新版本啊，yapi跟chrome 都是最新的版本。

**Comment by empl123** [comment]
@shouldnotappearcalm 如下：

[你看.txt](https://github.com/shouldnotappearcalm/yapi-plugin-interface-oauth2-token/files/4526456/default.txt)

**Comment by shouldnotappearcalm** [comment]
请求体，不是你返回的内容

**Comment by empl123** [comment]
@blackkeai 最新版本的google浏览器打不开安装的插件
![image](https://user-images.githubusercontent.com/23521894/80172248-15702280-861f-11ea-82e0-d8c868ac3ac3.png)

**Comment by empl123** [comment]
@shouldnotappearcalm 是这吗？
![image](https://user-images.githubusercontent.com/23521894/80172313-42243a00-861f-11ea-9e5e-bf7e2ea44e3b.png)

**Comment by shouldnotappearcalm** [comment]
@empl123 加我微信吧，gzr1191465097

**Comment by empl123** [comment]
@shouldnotappearcalm 谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢！

**Comment by shouldnotappearcalm** [comment]
破案， yapi 服务器 ping 不通题主的后端服务地址，导致请求获取 token 一直 pending
