### ISSUE TITLE
插件安装成功了，客户端编译报错

### ISSUE THREAD

**Issue by fengbinTester** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#21]
[error] ./client/components/Loading/Loading.js

/opt/my-yapi/vendors/client/components/Loading/Loading.js
  16:3  error  componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

✖ 1 problem (1 error, 0 warnings)

[error] ./client/components/AuthenticatedComponent.js

/opt/my-yapi/vendors/client/components/AuthenticatedComponent.js
  28:5  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components                       react/no-deprecated
  31:5  error  componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

✖ 2 problems (2 errors, 0 warnings)

[error] ./client/components/MyPopConfirm/MyPopConfirm.js

/opt/my-yapi/vendors/client/components/MyPopConfirm/MyPopConfirm.js
  29:3  error  componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

✖ 1 problem (1 error, 0 warnings)

[error] ./client/containers/Project/Project.js

/opt/my-yapi/vendors/client/containers/Project/Project.js
  44:9  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components                       react/no-deprecated
  59:9  error  componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

✖ 2 problems (2 errors, 0 warnings)

**Comment by shouldnotappearcalm** [comment]
这些 `deprecated` 的错误应该没啥影响吧

**Comment by fengbinTester** [comment]
客户端编译失败，所有的页面都是空白！
这是npm安装依赖情况
/root/nodejs/lib
├── express@4.17.1
├── express-generator@4.16.1
├── http-server@0.12.3
├── node-gyp@7.0.0
├── node-sass@4.14.1
├── npm@6.14.5
├── react@0.14.0
├── react-dom@0.14.0
├── react-slick@0.15.4
├── yapi-cli@1.5.0
├── yapi-vendor@1.9.2 -> /opt/my-yapi/vendors
└── ykit@0.8.13

npm ERR! peer dep missing: jquery@>=1.8.0, required by slick-carousel@1.8.1
npm ERR! peer dep missing: webpack@^3.0.0 || ^4.0.0, required by sass-loader@7.3.1
npm ERR! peer dep missing: markdown-it@>=8.4.2 <11.0.0, required by markdown-it-include@1.1.1
npm ERR! peer dep missing: mongoose@^4.1.12, required by mongoose-auto-increment@5.0.1
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.1, required by react-slick@0.15.4
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.1, required by react-slick@0.15.4
npm ERR! peer dep missing: jquery@>=1.8.0, required by slick-carousel@1.8.1

**Comment by shouldnotappearcalm** [comment]
要不你把`node_modules`删除一下重新安装

**Comment by fengbinTester** [comment]
目前版本是1.92，删除后，重新npm install
[root@10 vendors]# npm install
npm WARN markdown-it-include@1.1.1 requires a peer of markdown-it@>=8.4.2 <11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.3.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 39.768s

30 packages are looking for funding
  run `npm fund` for details

然后在/opt/my-yapi下
yapi unplugin --name yapi-plugin-interface-oauth2-token
然后仍报错
[error] ./client/components/Loading/Loading.js

/opt/my-yapi/vendors/client/components/Loading/Loading.js
16:3 error componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components react/no-deprecated

✖ 1 problem (1 error, 0 warnings)

[error] ./client/components/AuthenticatedComponent.js

/opt/my-yapi/vendors/client/components/AuthenticatedComponent.js
28:5 error componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components react/no-deprecated
31:5 error componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components react/no-deprecated

✖ 2 problems (2 errors, 0 warnings)

[error] ./client/components/MyPopConfirm/MyPopConfirm.js

/opt/my-yapi/vendors/client/components/MyPopConfirm/MyPopConfirm.js
29:3 error componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components react/no-deprecated

✖ 1 problem (1 error, 0 warnings)

[error] ./client/containers/Project/Project.js

/opt/my-yapi/vendors/client/containers/Project/Project.js
44:9 error componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components react/no-deprecated
59:9 error componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components react/no-deprecated

✖ 2 problems (2 errors, 0 warnings)
[error] ./client/containers/Project/Interface/InterfaceList/Run/AddColModal.js

/opt/my-yapi/vendors/client/containers/Project/Interface/InterfaceList/Run/AddColModal.js
  44:3  error  componentWillMount is deprecated since React 16.9.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components                       react/no-deprecated
  49:3  error  componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

✖ 2 problems (2 errors, 0 warnings)


[error] index@36beddf8d4fe18d20710.js from UglifyJs
SyntaxError: Unexpected token operator «=», expected punc «,» [../~/swagger-client/lib/index.js:51,0]

卸载插件成功，请重启服务器

**Comment by shouldnotappearcalm** [comment]
我先用 1.9.2 版本试一下

**Comment by shouldnotappearcalm** [comment]
我用 `1.9.2` 源码安装可以装上插件，也能正常运行，你手动装下 `node-sass` 看看呢 `npm install --registry http://npm.thunisoft.com`

**Comment by fengbinTester** [comment]
申请了你的群，帮忙通过下吧！
npm install是成功的。安装插件后，还是提示编译客户成功，提示然后仍报错，yapi打开空白。
以下是提示信息：
[error] ./client/components/Loading/Loading.js

/opt/my-yapi/vendors/client/components/Loading/Loading.js
16:3 error componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components react/no-deprecated

✖ 1 problem (1 error, 0 warnings)

[error] ./client/components/AuthenticatedComponent.js

**Comment by shouldnotappearcalm** [comment]
可视化部署安装会有问题，用源码部署可以解决

**Comment by TYOMI** [comment]
我用1.9.2的源码部署也出现了上述问题，方便提供下你源码部署的步骤吗？
16:3 error componentWillReceiveProps is deprecated since React 16.9.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components react/no-deprecated
