### ISSUE TITLE
获取token地址不正确

### ISSUE THREAD

**Issue by ColouredGlaze** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#28]
![image](https://user-images.githubusercontent.com/19931697/90091152-4dc77800-dd58-11ea-9d91-98feba531697.png)
这个是有什么判断规则吗，是地址填的不对，还是发送请求错误呢。

**Comment by shouldnotappearcalm** [comment]
yapi的服务器能解析 `plgx-gateway` 吗

**Comment by ColouredGlaze** [comment]
可以的

**Comment by shouldnotappearcalm** [comment]
参数那些都对么。看看 postman 能请求到么截个图

**Comment by ColouredGlaze** [comment]
可以了，是我的问题，参数填错地方了，工具很好用！非常感谢！

**Comment by shouldnotappearcalm** [comment]
觉得好可以给个star
