### ISSUE TITLE
多环境时候无法自动获取token

### ISSUE THREAD

**Issue by ColouredGlaze** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#29]
配置多个环境，第一个环境发起请求可以自动授权，第二个环境配置完之后（只修改了地址，地址映射的 ip 是一样的），点击校验，显示校验成功，使用第二个环境发起请求时返回 401 未授权。

**Comment by shouldnotappearcalm** [comment]
目前并发情况下还有点问题，有效时长可以选择设置为不同的时长

**Comment by ColouredGlaze** [comment]
![image](https://user-images.githubusercontent.com/19931697/90118918-7f0d6b80-dd8b-11ea-85a3-3d8ae4179ce7.png)
![image](https://user-images.githubusercontent.com/19931697/90118988-93e9ff00-dd8b-11ea-8476-ae054575c17e.png)
不行哦，我一个设置 12 小时，一个设置 5 小时，新增的环境还是不行

**Comment by shouldnotappearcalm** [comment]
你看看请求用的 token 确实有效么

**Comment by ColouredGlaze** [comment]
新增的环境发起请求没有携带 token

**Comment by shouldnotappearcalm** [comment]
那你看看环境配置里面请求头有么

**Comment by ColouredGlaze** [comment]
![image](https://user-images.githubusercontent.com/19931697/90120013-e2e46400-dd8c-11ea-8803-aeec8a330a57.png)
有的

**Comment by shouldnotappearcalm** [comment]
![image](https://user-images.githubusercontent.com/20592210/90120380-4373a100-dd8d-11ea-872e-109ed94a9061.png)

你看看这边

**Comment by ColouredGlaze** [comment]
![image](https://user-images.githubusercontent.com/19931697/90120542-6ef68b80-dd8d-11ea-9859-7f756982dfb3.png)

**Comment by ColouredGlaze** [comment]
没有哦

**Comment by ColouredGlaze** [comment]
![image](https://user-images.githubusercontent.com/19931697/90120983-fd6b0d00-dd8d-11ea-9dcf-e0f7d0889bf3.png)
控制台有信息

**Comment by ColouredGlaze** [comment]
我把第二个环境删了，第一个环境的头部也删了，重新发起请求，第一个环境的请求也无法认证了

**Comment by shouldnotappearcalm** [comment]
我咋感觉是你接口问题呢，你再用 postman 调试一下你的接口

**Comment by ColouredGlaze** [comment]
![image](https://user-images.githubusercontent.com/19931697/90121584-bb8e9680-dd8e-11ea-907f-b15ddb27f393.png)
![image](https://user-images.githubusercontent.com/19931697/90121625-c9441c00-dd8e-11ea-87da-cc291ca17c45.png)
接口 postman 是没有问题的

**Comment by shouldnotappearcalm** [comment]
那有点奇怪了

**Comment by ColouredGlaze** [comment]
yapi 版本是：1.9.2
"yapi-plugin-interface-oauth2-token": "^1.2.3"

看下能否复现

**Comment by shouldnotappearcalm** [comment]
我有空试试

**Comment by shouldnotappearcalm** [comment]
建议你还是再插件哪儿配错没有

**Comment by ColouredGlaze** [comment]
> 建议你还是再检查哪儿配错没有

今天重新试了一下，删除所有数据，重新安装yapi，重现了。

**Comment by shouldnotappearcalm** [comment]
重现了什么

**Comment by ColouredGlaze** [comment]
前面提到的问题，第一个环境可以，第二个环境不能实现自动获取 token

**Comment by shouldnotappearcalm** [comment]
有这么奇怪。。我们都是N个环境都是可以的

**Comment by ColouredGlaze** [comment]
你们用的 yapi 是哪个版本的

**Comment by shouldnotappearcalm** [comment]
不是最新的，跟这个没啥关系

**Comment by ColouredGlaze** [comment]
![image](https://user-images.githubusercontent.com/19931697/90376322-d7ed4480-e0a8-11ea-8112-75f145baa81a.png)
发现了这个，看下有帮助吗

**Comment by ColouredGlaze** [comment]
log: token更新定时器触发, getTokenUrl:http://test1-pigx-gateway:9999/auth/oauth/token
log: token更新定时器触发, getTokenUrl:http://dev-pigx-gateway:9999/auth/oauth/token
log: token更新定时器触发, getTokenUrl:http://local-pigx-gateway:9999/auth/oauth/token
log: 定时器触发, syncJsonUrl:http://pigx-gateway:9999/api/cc/v2/api-docs,合并模式:merge
(node:15120) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.
log: 定时器触发, syncJsonUrl:http://pigx-gateway:9999/api/cc/v2/api-docs,合并模式:merge
log: 定时器触发, syncJsonUrl:http://pigx-gateway:9999/api/cc/v2/api-docs,合并模式:merge
log: 获取数据失败Validation failed: members.0.role: `guest` is not a valid enum value for path `role`.
log: 获取数据失败Validation failed: members.0.role: `guest` is not a valid enum value for path `role`.
log: 获取数据失败Validation failed: members.0.role: `guest` is not a valid enum value for path `role`.
(node:15120) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:15120) UnhandledPromiseRejectionWarning: MongoError: Performing an update on the path '_id' would modify the immutable field '_id'
    at Function.create (D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\error.js:44:12)
    at toError (D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\utils.js:150:22)
    at D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\operations\common_functions.js:373:39
    at handler (D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\sdam\topology.js:973:24)
    at D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\sdam\server.js:437:5
    at D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\connection\pool.js:420:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:15120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15120) UnhandledPromiseRejectionWarning: MongoError: Performing an update on the path '_id' would modify the immutable field '_id'
    at Function.create (D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\error.js:44:12)
    at toError (D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\utils.js:150:22)
    at D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\operations\common_functions.js:373:39
    at handler (D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\sdam\topology.js:973:24)
    at D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\sdam\server.js:437:5
    at D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\connection\pool.js:420:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:15120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15120) UnhandledPromiseRejectionWarning: MongoError: Performing an update on the path '_id' would modify the immutable field '_id'
    at Function.create (D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\error.js:44:12)
    at toError (D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\utils.js:150:22)
    at D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\operations\common_functions.js:373:39
    at handler (D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\sdam\topology.js:973:24)
    at D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\sdam\server.js:437:5
    at D:\yapi\vendors\node_modules\mongoose\node_modules\mongodb\lib\core\connection\pool.js:420:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:15120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by shouldnotappearcalm** [comment]
我晚上回去装个 `1.9.2` 试试吧

**Comment by ColouredGlaze** [comment]
把已经存在的 token 删除，然后重新点击校验，校验成功，然后点击保存，提示保存成功，控制台报错：

log: 获取数据失败Validation failed: members.0.role: `guest` is not a valid enum value for path `role`.

**Comment by ColouredGlaze** [comment]
> 把已经存在的 token 删除，然后重新点击校验，校验成功，然后点击保存，提示保存成功，控制台报错：
> 
> log: 获取数据失败Validation failed: members.0.role: `guest` is not a valid enum value for path `role`.

然后环境查看没有 token

**Comment by shouldnotappearcalm** [comment]
你有空的话可以看看源码研究一下

**Comment by ColouredGlaze** [comment]
哈哈哈，这就有点为难我了，我后端的，我试试吧！

**Comment by shouldnotappearcalm** [comment]
嗯嗯，这个问题蛮奇怪的，昨晚回去没来得及看

**Comment by ColouredGlaze** [comment]
哈哈哈！找到了，yapi 的问题，给他们提 pr 去！

**Comment by shouldnotappearcalm** [comment]
yapi 什么问题呢，我看要不要兼容一下

**Comment by ColouredGlaze** [comment]
是 yapi 的 bug，角色少了个访客，更新的时候角色字段校验少了 guest

**Comment by ColouredGlaze** [comment]
> 是 yapi 的 bug，角色少了个访客，更新的时候角色字段校验少了 guest

所以保存的时候就有这个：
log: 获取数据失败Validation failed: members.0.role: guest is not a valid enum value for path role.

**Comment by ColouredGlaze** [comment]
你把你小组内的某个成员设置成访客，然后更新token，点击保存，就会重现了

**Comment by shouldnotappearcalm** [comment]
哦这个问题应该一直就有存在的。。不光是 1.9.2 版本，那我这边可能需要考虑一下兼容，要不你先让组长或者管理员去配置这个东西

**Comment by ColouredGlaze** [comment]
嗯嗯，我设置下，这个 issue 可以关闭了哈！谢谢！

**Comment by shouldnotappearcalm** [comment]
嗯嗯，感谢您帮助发现问题
