### ISSUE TITLE
安装插件报错了，yapi也无法启动。。。

### ISSUE THREAD

**Issue by kira5271** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#3]
$ yapi plugin --name yapi-plugin-interface-oauth2-token
正在下载插件...

> node-sass@4.12.0 install E:\yapi\vendors\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node":

connect ETIMEDOUT 52.216.200.131:443

Timed out whilst downloading the prebuilt binary

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 postinstall E:\yapi\vendors\node_modules\node-sass
> node scripts/build.js

Building: D:\nodejs\node.exe E:\yapi\vendors\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cfl                                                                                                                                              ags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\nodejs\\node.exe',
gyp verb cli   'E:\\yapi\\vendors\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\yapi\vendors\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\yapi\vendors\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\yapi\vendors\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\yapi\vendors\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\yapi\vendors\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\yapi\vendors\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\yapi\vendors\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\yapi\vendors\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\yapi\vendors\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\yapi\vendors\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\yapi\vendors\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\yapi\vendors\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (E:\\yapi\\vendors\\node_modules\\which\\which.js:                                                                                                                                              13:12)\n    at F (E:\\yapi\\vendors\\node_modules\\which\\which.js:68:19)\n    at E (E:\\yapi\\vendors\\node_modules\\which\\whic                                                                                                                                              h.js:80:29)\n    at E:\\yapi\\vendors\\node_modules\\which\\which.js:89:16\n    at E:\\yapi\\vendors\\node_modules\\isexe\\index.                                                                                                                                              js:42:5\n    at E:\\yapi\\vendors\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\fengkaijun\AppData\Local\Programs\Python\Python37\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\fengkaijun\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print                                                                                                                                               "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:198:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\nodejs\\node.exe" "E:\\yapi\\vendors\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--li                                                                                                                                              bsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\yapi\vendors\node_modules\node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependenc                                                                                                                                              ies yourself.
npm WARN sass-loader@7.1.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies                                                                                                                                               yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yoursel                                                                                                                                              f.
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies                                                                                                                                               yourself.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependen                                                                                                                                              cies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (curre                                                                                                                                              nt: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (curre                                                                                                                                              nt: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fengkaijun\AppData\Roaming\npm-cache\_logs\2019-08-02T11_45_05_017Z-debug.log
更新插件成功
正在安装依赖...

> node-sass@4.12.0 install E:\yapi\vendors\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.12.0/win32-x64-64_binding.node":

connect ETIMEDOUT 52.216.229.51:443

Timed out whilst downloading the prebuilt binary

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.12.0 postinstall E:\yapi\vendors\node_modules\node-sass
> node scripts/build.js

Building: D:\nodejs\node.exe E:\yapi\vendors\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cfl                                                                                                                                              ags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\\nodejs\\node.exe',
gyp verb cli   'E:\\yapi\\vendors\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\yapi\vendors\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\yapi\vendors\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\yapi\vendors\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\yapi\vendors\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\yapi\vendors\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\yapi\vendors\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\yapi\vendors\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\yapi\vendors\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\yapi\vendors\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\yapi\vendors\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\yapi\vendors\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\yapi\vendors\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack:
gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundError (E:\\yapi\\vendors\\node_modules\\which\\which.js:                                                                                                                                              13:12)\n    at F (E:\\yapi\\vendors\\node_modules\\which\\which.js:68:19)\n    at E (E:\\yapi\\vendors\\node_modules\\which\\whic                                                                                                                                              h.js:80:29)\n    at E:\\yapi\\vendors\\node_modules\\which\\which.js:89:16\n    at E:\\yapi\\vendors\\node_modules\\isexe\\index.                                                                                                                                              js:42:5\n    at E:\\yapi\\vendors\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\fengkaijun\AppData\Local\Programs\Python\Python37\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\fengkaijun\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print                                                                                                                                               "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:198:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\nodejs\\node.exe" "E:\\yapi\\vendors\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--li                                                                                                                                              bsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\yapi\vendors\node_modules\node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependenc                                                                                                                                              ies yourself.
npm WARN sass-loader@7.1.0 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies                                                                                                                                               yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yoursel                                                                                                                                              f.
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies                                                                                                                                               yourself.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependen                                                                                                                                              cies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (curre                                                                                                                                              nt: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (curre                                                                                                                                              nt: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fengkaijun\AppData\Roaming\npm-cache\_logs\2019-08-02T11_46_02_583Z-debug.log
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'yapi-plugin-interface-oauth2-token'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at getPluginConfig (E:\yapi\vendors\common\plugin.js:8:20)
    at plugins.map.item (E:\yapi\vendors\common\plugin.js:39:22)
    at Array.map (<anonymous>)
    at Object.exports.initPlugins (E:\yapi\vendors\common\plugin.js:33:21)
    at initPlugins (E:\yapi\vendors\ykit.config.js:42:30)
    at Object.<anonymous> (E:\yapi\vendors\ykit.config.js:61:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
编译客户端成功，请重启服务器

**Comment by shouldnotappearcalm** [comment]
你用docker启动的yapi么

**Comment by kira5271** [comment]
并不是发自我的华为手机-------- 原始邮件 --------主题：Re: [shouldnotappearcalm/yapi-plugin-interface-oauth2-token] 安装插件报错了，yapi也无法启动。。。 (#3)发件人：losergzr 收件人：shouldnotappearcalm/yapi-plugin-interface-oauth2-token 抄送：kira5271 <447586592@qq.com>,Author 你用docker启动的yapi么

**Comment by shouldnotappearcalm** [comment]
你这个是包下不下来啊

**Comment by kira5271** [comment]
正常用npm下载的yapi-cli发自我的华为手机-------- 原始邮件 --------主题：Re: [shouldnotappearcalm/yapi-plugin-interface-oauth2-token] 安装插件报错了，yapi也无法启动。。。 (#3)发件人：losergzr 收件人：shouldnotappearcalm/yapi-plugin-interface-oauth2-token 抄送：kira5271 <447586592@qq.com>,Author 你这个是包下不下来啊

**Comment by kira5271** [comment]
我看node_module已经有了，难道安装目录不对？发自我的华为手机-------- 原始邮件 --------主题：Re: [shouldnotappearcalm/yapi-plugin-interface-oauth2-token] 安装插件报错了，yapi也无法启动。。。 (#3)发件人：losergzr 收件人：shouldnotappearcalm/yapi-plugin-interface-oauth2-token 抄送：kira5271 <447586592@qq.com>,Author 你这个是包下不下来啊

**Comment by shouldnotappearcalm** [comment]
要不你先nnpm装下这个依赖再装插件呢，npm install的时候指定下淘宝源

**Comment by shouldnotappearcalm** [comment]
先手动安装下 node-sass，再安装插件，`npm install node-sass`

**Comment by lsw1991abc** [comment]
本地想在插件中增加几个参数
在yapi中link yapi-plugin-interface-oauth2-token之后，提示好多module找不到
能否提供一下帮助

**Comment by shouldnotappearcalm** [comment]
贴一下错误信息，要不你新开个 `Issue`

**Comment by shouldnotappearcalm** [comment]
@lsw1991abc

**Comment by lianjl256** [comment]
安装插件后系统，整个yapi都无法使用
 yapi plugin --name yapi-plugin-notifier

![image](https://user-images.githubusercontent.com/9443709/141748431-016f6752-922c-4157-adee-45349f268adc.png)

![image](https://user-images.githubusercontent.com/9443709/141748343-2fd8458b-79ed-48b3-8158-85a3db4e68d3.png)
