### ISSUE TITLE
手动安装node-sass报错解决

### ISSUE THREAD

**Issue by xmherz** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#30]
![image](https://user-images.githubusercontent.com/38306769/91272861-fe993280-e7ae-11ea-8940-d0dd12aa3501.png)

解决方式
npm install --unsafe-perm -g node-sass

**Comment by shouldnotappearcalm** [comment]
这种是解决了对吧

**Comment by shouldnotappearcalm** [comment]
还遇到 node-sass 的一个问题，用非 root 用户安装可以解决 `https://stackoverflow.com/questions/55668065/npm-error-error-eacces-permission-denied-mkdir-node-sass-build`

**Comment by xmherz** [comment]
并没有真正解决，手工安装完node-sass后，再安装插件仍然会报上面的错误。

后面看到这个帖子，我的node版本是V10  modules:64 ，而npm install node-sass默认装的是最新版本，版本对应不上。
https://segmentfault.com/a/1190000020993365?utm_source=tag-newest

所以，最后，我是把node版本升级到最新的才解决了这个问题。

**Comment by shouldnotappearcalm** [comment]
可以的，老哥牛逼
