### ISSUE TITLE
自制https证书，获取鉴权时提示获取数据失败

### ISSUE THREAD

**Issue by fengbinTester** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#35]
日志信息：
![image](https://user-images.githubusercontent.com/42330540/97435934-226a2780-195c-11eb-930e-d7df42d151aa.png)
设置：
![image](https://user-images.githubusercontent.com/42330540/97436704-5bef6280-195d-11eb-96cf-6618f0bf1274.png)
点击检查提示：校验地址返回错误状态,unable to verify the first certificate

**Comment by shouldnotappearcalm** [comment]
我突然想了下，你是不是在你们的 yapi 服务器上导入你们的自签名证书是不是就可以了

**Comment by shouldnotappearcalm** [comment]
@fengbinTester 我发布了 1.3.0 版本支持了 https 自签名证书，你可以升级试试
