### ISSUE TITLE
获取token地址不正确

### ISSUE THREAD

**Issue by ColouredGlaze** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#37]
使用 postman 测试没问题，yapi 校验有问题

yapi：
![image](https://user-images.githubusercontent.com/19931697/102201543-3dd7c480-3f01-11eb-8ea9-3632c608d196.png)

postman：
![image](https://user-images.githubusercontent.com/19931697/102201644-5d6eed00-3f01-11eb-9550-a67d4dcf261f.png)

![image](https://user-images.githubusercontent.com/19931697/102201744-77103480-3f01-11eb-9756-ba1eb695c24f.png)

**Comment by shouldnotappearcalm** [comment]
yapi 服务器上能 ping 通你请求的那个域名吗

**Comment by shouldnotappearcalm** [comment]
如果觉得 github 回 issue 麻烦的话，可以加我微信，Z3pyMTE5MTQ2NTA5Nwo= (base64 解码一下)

**Comment by ColouredGlaze** [comment]
> yapi 服务器上能 ping 通你请求的那个域名吗

可以 ping 通，postman 也能成功登陆

**Comment by shouldnotappearcalm** [comment]
要不你加一下我微信咱们说起来方便点，上面贴的有我微信

**Comment by shouldnotappearcalm** [comment]
结案，因为服务器上不能解析这个配置的域名，所以请求会失败
