### ISSUE TITLE
token如何设置呢

### ISSUE THREAD

**Issue by yizhishang** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#6]
1. 开关“是否开启自动获取token” 调整后没什么用啊
2. 通过鉴权的接口，获取的数据，能自动设置其他接口中header里面的Authorization字段的值吗

**Comment by shouldnotappearcalm** [comment]
会统一加到所有接口的 header 上啊，你看环境配置->环境列表

**Comment by yizhishang** [comment]
好像没有生效

**Comment by shouldnotappearcalm** [comment]
配置的接口能正常访问吗

**Comment by yizhishang** [comment]
可以的，我在postman测试是ok的

**Comment by shouldnotappearcalm** [comment]
是 get 请求吗，cron 表达式怎么配置的

**Comment by shouldnotappearcalm** [comment]
错了。。没有 cron 表达式。。返回的结果是满足规范的吗

**Comment by yizhishang** [comment]
![image](https://user-images.githubusercontent.com/12756407/67379962-3c8c5f80-f5bc-11e9-9da8-2d8eaacf25bf.png)
这样配置的

**Comment by shouldnotappearcalm** [comment]
能把链接粘贴发一下在这里吗

**Comment by yizhishang** [comment]
内网连接，你访问不了哦

**Comment by shouldnotappearcalm** [comment]
看看日志有什么报错吗

**Comment by yizhishang** [comment]
postman我先设置获取keycloak的token后，然后跑接口ok
![image](https://user-images.githubusercontent.com/12756407/67380596-2df27800-f5bd-11e9-945c-d076bf2aa7ba.png)

在yapi里面测试：结果如下
![image](https://user-images.githubusercontent.com/12756407/67380649-419dde80-f5bd-11e9-80b8-db8c1b67f106.png)

**Comment by shouldnotappearcalm** [comment]
能截图 postman 里面调用请求 token 接口吗

**Comment by yizhishang** [comment]
![image](https://user-images.githubusercontent.com/12756407/67380810-76119a80-f5bd-11e9-9f12-1e7c0745ab2a.png)
日志

**Comment by yizhishang** [comment]
![image](https://user-images.githubusercontent.com/12756407/67380841-83c72000-f5bd-11e9-8f82-fb0fd6803c27.png)

**Comment by yizhishang** [comment]
![image](https://user-images.githubusercontent.com/12756407/67380905-9a6d7700-f5bd-11e9-8358-4e8bd21a3512.png)
yapidan单独调用获取token也没问题

**Comment by shouldnotappearcalm** [comment]
恩、、、我知道了。。。我这个是发的 `GET` 请求，你们这个获取 token 的接口是个 `POST` 请求居然。。。

**Comment by yizhishang** [comment]
yapi版本1.8.4

**Comment by yizhishang** [comment]
能升级下插件吗

**Comment by yizhishang** [comment]
一般获取token都是post请求吧

**Comment by shouldnotappearcalm** [comment]
。。这个我也还得开发+测试，没那么快，你们可以新增个接口做下适配。。一般都是 `GET` 吧

**Comment by yizhishang** [comment]
或者可以支持自己设置请求方式。
keycloak的提供的接口都是post方式呢

**Comment by shouldnotappearcalm** [comment]
那我最近开发下支持 `POST` 吧

**Comment by yizhishang** [comment]
好的，麻烦了。
然后我看post里面填写获取token的路径没有规定是get还是post。
建议你做成可调整的^_^

**Comment by shouldnotappearcalm** [comment]
好的，我尽快开发出来

**Comment by eyotang** [comment]
get和post都需要，最好能做成可配置的。

获取字段，也要可配置比较好。

有的鉴权接口是放在响应头的Cookie里面，有的是reponse的body里面。

**Comment by shouldnotappearcalm** [comment]
@yizhishang 老哥你要的功能已经由 @eyotang 老哥开发完成并且发了

**Comment by yizhishang** [comment]
> 完成
可以，可以
